//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DysonNetwork.Sphere.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DysonNetwork.Sphere.Resources.Localization.NotificationResource", typeof(NotificationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ChatInviteTitle {
            get {
                return ResourceManager.GetString("ChatInviteTitle", resourceCulture);
            }
        }
        
        internal static string ChatInviteBody {
            get {
                return ResourceManager.GetString("ChatInviteBody", resourceCulture);
            }
        }
        
        internal static string ChatInviteDirectBody {
            get {
                return ResourceManager.GetString("ChatInviteDirectBody", resourceCulture);
            }
        }
        
        internal static string RealmInviteTitle {
            get {
                return ResourceManager.GetString("RealmInviteTitle", resourceCulture);
            }
        }
        
        internal static string RealmInviteBody {
            get {
                return ResourceManager.GetString("RealmInviteBody", resourceCulture);
            }
        }
        
        internal static string PostSubscriptionTitle {
            get {
                return ResourceManager.GetString("PostSubscriptionTitle", resourceCulture);
            }
        }
        
        internal static string PostReactTitle {
            get {
                return ResourceManager.GetString("PostReactTitle", resourceCulture);
            }
        }
        
        internal static string PostReactBody {
            get {
                return ResourceManager.GetString("PostReactBody", resourceCulture);
            }
        }
        
        internal static string PostReactContentBody {
            get {
                return ResourceManager.GetString("PostReactContentBody", resourceCulture);
            }
        }
    }
}
