// <auto-generated />
using System;
using System.Text.Json;
using DysonNetwork.Fitness;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DysonNetwork.Fitness.Migrations
{
    [DbContext(typeof(AppDatabase))]
    [Migration("20260414173247_UpdateFitnessMetricColumns")]
    partial class UpdateFitnessMetricColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DysonNetwork.Fitness.Goals.SnFitnessGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool>("AutoUpdateProgress")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_update_progress");

                    b.Property<int?>("BoundMetricType")
                        .HasColumnType("integer")
                        .HasColumnName("bound_metric_type");

                    b.Property<int?>("BoundWorkoutType")
                        .HasColumnType("integer")
                        .HasColumnName("bound_workout_type");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentRepetition")
                        .HasColumnType("integer")
                        .HasColumnName("current_repetition");

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("current_value");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<Instant?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("GoalType")
                        .HasColumnType("integer")
                        .HasColumnName("goal_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("ParentGoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_goal_id");

                    b.Property<int?>("RepeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_count");

                    b.Property<int>("RepeatInterval")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_interval");

                    b.Property<int>("RepeatType")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_type");

                    b.Property<Instant>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("target_value");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_fitness_goals");

                    b.ToTable("fitness_goals", (string)null);
                });

            modelBuilder.Entity("DysonNetwork.Fitness.Metrics.SnFitnessMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_id");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer")
                        .HasColumnName("metric_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("notes");

                    b.Property<Instant>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_fitness_metrics");

                    b.ToTable("fitness_metrics", (string)null);
                });

            modelBuilder.Entity("DysonNetwork.Fitness.Workouts.SnWorkout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("average_heart_rate");

                    b.Property<decimal?>("AverageSpeed")
                        .HasColumnType("numeric")
                        .HasColumnName("average_speed");

                    b.Property<int?>("CaloriesBurned")
                        .HasColumnType("integer")
                        .HasColumnName("calories_burned");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("numeric")
                        .HasColumnName("distance");

                    b.Property<string>("DistanceUnit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("distance_unit");

                    b.Property<Duration?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<decimal?>("ElevationGain")
                        .HasColumnType("numeric")
                        .HasColumnName("elevation_gain");

                    b.Property<Instant?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_id");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("max_heart_rate");

                    b.Property<decimal?>("MaxSpeed")
                        .HasColumnType("numeric")
                        .HasColumnName("max_speed");

                    b.Property<JsonDocument>("Meta")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("notes");

                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source");

                    b.Property<Instant>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_workouts");

                    b.ToTable("workouts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
