// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: auth.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace DysonNetwork.Shared.Proto {
  public static partial class DyAuthService
  {
    static readonly string __ServiceName = "proto.DyAuthService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyAuthenticateRequest> __Marshaller_proto_DyAuthenticateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyAuthenticateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyAuthenticateResponse> __Marshaller_proto_DyAuthenticateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyAuthenticateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyValidatePinRequest> __Marshaller_proto_DyValidatePinRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyValidatePinRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyValidateResponse> __Marshaller_proto_DyValidateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyValidateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyValidateCaptchaRequest> __Marshaller_proto_DyValidateCaptchaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyValidateCaptchaRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyAuthenticateRequest, global::DysonNetwork.Shared.Proto.DyAuthenticateResponse> __Method_Authenticate = new grpc::Method<global::DysonNetwork.Shared.Proto.DyAuthenticateRequest, global::DysonNetwork.Shared.Proto.DyAuthenticateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Authenticate",
        __Marshaller_proto_DyAuthenticateRequest,
        __Marshaller_proto_DyAuthenticateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyValidatePinRequest, global::DysonNetwork.Shared.Proto.DyValidateResponse> __Method_ValidatePin = new grpc::Method<global::DysonNetwork.Shared.Proto.DyValidatePinRequest, global::DysonNetwork.Shared.Proto.DyValidateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ValidatePin",
        __Marshaller_proto_DyValidatePinRequest,
        __Marshaller_proto_DyValidateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyValidateCaptchaRequest, global::DysonNetwork.Shared.Proto.DyValidateResponse> __Method_ValidateCaptcha = new grpc::Method<global::DysonNetwork.Shared.Proto.DyValidateCaptchaRequest, global::DysonNetwork.Shared.Proto.DyValidateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ValidateCaptcha",
        __Marshaller_proto_DyValidateCaptchaRequest,
        __Marshaller_proto_DyValidateResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DysonNetwork.Shared.Proto.AuthReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DyAuthService</summary>
    [grpc::BindServiceMethod(typeof(DyAuthService), "BindService")]
    public abstract partial class DyAuthServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyAuthenticateResponse> Authenticate(global::DysonNetwork.Shared.Proto.DyAuthenticateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyValidateResponse> ValidatePin(global::DysonNetwork.Shared.Proto.DyValidatePinRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyValidateResponse> ValidateCaptcha(global::DysonNetwork.Shared.Proto.DyValidateCaptchaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DyAuthService</summary>
    public partial class DyAuthServiceClient : grpc::ClientBase<DyAuthServiceClient>
    {
      /// <summary>Creates a new client for DyAuthService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DyAuthServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DyAuthService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DyAuthServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DyAuthServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DyAuthServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyAuthenticateResponse Authenticate(global::DysonNetwork.Shared.Proto.DyAuthenticateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Authenticate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyAuthenticateResponse Authenticate(global::DysonNetwork.Shared.Proto.DyAuthenticateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Authenticate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyAuthenticateResponse> AuthenticateAsync(global::DysonNetwork.Shared.Proto.DyAuthenticateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AuthenticateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyAuthenticateResponse> AuthenticateAsync(global::DysonNetwork.Shared.Proto.DyAuthenticateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Authenticate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyValidateResponse ValidatePin(global::DysonNetwork.Shared.Proto.DyValidatePinRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ValidatePin(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyValidateResponse ValidatePin(global::DysonNetwork.Shared.Proto.DyValidatePinRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ValidatePin, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyValidateResponse> ValidatePinAsync(global::DysonNetwork.Shared.Proto.DyValidatePinRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ValidatePinAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyValidateResponse> ValidatePinAsync(global::DysonNetwork.Shared.Proto.DyValidatePinRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ValidatePin, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyValidateResponse ValidateCaptcha(global::DysonNetwork.Shared.Proto.DyValidateCaptchaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ValidateCaptcha(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyValidateResponse ValidateCaptcha(global::DysonNetwork.Shared.Proto.DyValidateCaptchaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ValidateCaptcha, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyValidateResponse> ValidateCaptchaAsync(global::DysonNetwork.Shared.Proto.DyValidateCaptchaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ValidateCaptchaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyValidateResponse> ValidateCaptchaAsync(global::DysonNetwork.Shared.Proto.DyValidateCaptchaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ValidateCaptcha, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DyAuthServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DyAuthServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DyAuthServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Authenticate, serviceImpl.Authenticate)
          .AddMethod(__Method_ValidatePin, serviceImpl.ValidatePin)
          .AddMethod(__Method_ValidateCaptcha, serviceImpl.ValidateCaptcha).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DyAuthServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Authenticate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyAuthenticateRequest, global::DysonNetwork.Shared.Proto.DyAuthenticateResponse>(serviceImpl.Authenticate));
      serviceBinder.AddMethod(__Method_ValidatePin, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyValidatePinRequest, global::DysonNetwork.Shared.Proto.DyValidateResponse>(serviceImpl.ValidatePin));
      serviceBinder.AddMethod(__Method_ValidateCaptcha, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyValidateCaptchaRequest, global::DysonNetwork.Shared.Proto.DyValidateResponse>(serviceImpl.ValidateCaptcha));
    }

  }
  public static partial class DyPermissionService
  {
    static readonly string __ServiceName = "proto.DyPermissionService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyHasPermissionRequest> __Marshaller_proto_DyHasPermissionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyHasPermissionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyHasPermissionResponse> __Marshaller_proto_DyHasPermissionResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyHasPermissionResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyGetPermissionRequest> __Marshaller_proto_DyGetPermissionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyGetPermissionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyGetPermissionResponse> __Marshaller_proto_DyGetPermissionResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyGetPermissionResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeRequest> __Marshaller_proto_DyAddPermissionNodeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyAddPermissionNodeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeResponse> __Marshaller_proto_DyAddPermissionNodeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyAddPermissionNodeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupRequest> __Marshaller_proto_DyAddPermissionNodeToGroupRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupResponse> __Marshaller_proto_DyAddPermissionNodeToGroupResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeRequest> __Marshaller_proto_DyRemovePermissionNodeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeResponse> __Marshaller_proto_DyRemovePermissionNodeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupRequest> __Marshaller_proto_DyRemovePermissionNodeFromGroupRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupResponse> __Marshaller_proto_DyRemovePermissionNodeFromGroupResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyHasPermissionRequest, global::DysonNetwork.Shared.Proto.DyHasPermissionResponse> __Method_HasPermission = new grpc::Method<global::DysonNetwork.Shared.Proto.DyHasPermissionRequest, global::DysonNetwork.Shared.Proto.DyHasPermissionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HasPermission",
        __Marshaller_proto_DyHasPermissionRequest,
        __Marshaller_proto_DyHasPermissionResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyGetPermissionRequest, global::DysonNetwork.Shared.Proto.DyGetPermissionResponse> __Method_GetPermission = new grpc::Method<global::DysonNetwork.Shared.Proto.DyGetPermissionRequest, global::DysonNetwork.Shared.Proto.DyGetPermissionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPermission",
        __Marshaller_proto_DyGetPermissionRequest,
        __Marshaller_proto_DyGetPermissionResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeRequest, global::DysonNetwork.Shared.Proto.DyAddPermissionNodeResponse> __Method_AddPermissionNode = new grpc::Method<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeRequest, global::DysonNetwork.Shared.Proto.DyAddPermissionNodeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddPermissionNode",
        __Marshaller_proto_DyAddPermissionNodeRequest,
        __Marshaller_proto_DyAddPermissionNodeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupRequest, global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupResponse> __Method_AddPermissionNodeToGroup = new grpc::Method<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupRequest, global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddPermissionNodeToGroup",
        __Marshaller_proto_DyAddPermissionNodeToGroupRequest,
        __Marshaller_proto_DyAddPermissionNodeToGroupResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeRequest, global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeResponse> __Method_RemovePermissionNode = new grpc::Method<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeRequest, global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemovePermissionNode",
        __Marshaller_proto_DyRemovePermissionNodeRequest,
        __Marshaller_proto_DyRemovePermissionNodeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupRequest, global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupResponse> __Method_RemovePermissionNodeFromGroup = new grpc::Method<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupRequest, global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemovePermissionNodeFromGroup",
        __Marshaller_proto_DyRemovePermissionNodeFromGroupRequest,
        __Marshaller_proto_DyRemovePermissionNodeFromGroupResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DysonNetwork.Shared.Proto.AuthReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of DyPermissionService</summary>
    [grpc::BindServiceMethod(typeof(DyPermissionService), "BindService")]
    public abstract partial class DyPermissionServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyHasPermissionResponse> HasPermission(global::DysonNetwork.Shared.Proto.DyHasPermissionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyGetPermissionResponse> GetPermission(global::DysonNetwork.Shared.Proto.DyGetPermissionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeResponse> AddPermissionNode(global::DysonNetwork.Shared.Proto.DyAddPermissionNodeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupResponse> AddPermissionNodeToGroup(global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeResponse> RemovePermissionNode(global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupResponse> RemovePermissionNodeFromGroup(global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DyPermissionService</summary>
    public partial class DyPermissionServiceClient : grpc::ClientBase<DyPermissionServiceClient>
    {
      /// <summary>Creates a new client for DyPermissionService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DyPermissionServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DyPermissionService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DyPermissionServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DyPermissionServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DyPermissionServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyHasPermissionResponse HasPermission(global::DysonNetwork.Shared.Proto.DyHasPermissionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HasPermission(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyHasPermissionResponse HasPermission(global::DysonNetwork.Shared.Proto.DyHasPermissionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_HasPermission, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyHasPermissionResponse> HasPermissionAsync(global::DysonNetwork.Shared.Proto.DyHasPermissionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HasPermissionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyHasPermissionResponse> HasPermissionAsync(global::DysonNetwork.Shared.Proto.DyHasPermissionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_HasPermission, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyGetPermissionResponse GetPermission(global::DysonNetwork.Shared.Proto.DyGetPermissionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPermission(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyGetPermissionResponse GetPermission(global::DysonNetwork.Shared.Proto.DyGetPermissionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPermission, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyGetPermissionResponse> GetPermissionAsync(global::DysonNetwork.Shared.Proto.DyGetPermissionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPermissionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyGetPermissionResponse> GetPermissionAsync(global::DysonNetwork.Shared.Proto.DyGetPermissionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPermission, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyAddPermissionNodeResponse AddPermissionNode(global::DysonNetwork.Shared.Proto.DyAddPermissionNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddPermissionNode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyAddPermissionNodeResponse AddPermissionNode(global::DysonNetwork.Shared.Proto.DyAddPermissionNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddPermissionNode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeResponse> AddPermissionNodeAsync(global::DysonNetwork.Shared.Proto.DyAddPermissionNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddPermissionNodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeResponse> AddPermissionNodeAsync(global::DysonNetwork.Shared.Proto.DyAddPermissionNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddPermissionNode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupResponse AddPermissionNodeToGroup(global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddPermissionNodeToGroup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupResponse AddPermissionNodeToGroup(global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddPermissionNodeToGroup, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupResponse> AddPermissionNodeToGroupAsync(global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddPermissionNodeToGroupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupResponse> AddPermissionNodeToGroupAsync(global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddPermissionNodeToGroup, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeResponse RemovePermissionNode(global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemovePermissionNode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeResponse RemovePermissionNode(global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemovePermissionNode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeResponse> RemovePermissionNodeAsync(global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemovePermissionNodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeResponse> RemovePermissionNodeAsync(global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemovePermissionNode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupResponse RemovePermissionNodeFromGroup(global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemovePermissionNodeFromGroup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupResponse RemovePermissionNodeFromGroup(global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemovePermissionNodeFromGroup, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupResponse> RemovePermissionNodeFromGroupAsync(global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemovePermissionNodeFromGroupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupResponse> RemovePermissionNodeFromGroupAsync(global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemovePermissionNodeFromGroup, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DyPermissionServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DyPermissionServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DyPermissionServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_HasPermission, serviceImpl.HasPermission)
          .AddMethod(__Method_GetPermission, serviceImpl.GetPermission)
          .AddMethod(__Method_AddPermissionNode, serviceImpl.AddPermissionNode)
          .AddMethod(__Method_AddPermissionNodeToGroup, serviceImpl.AddPermissionNodeToGroup)
          .AddMethod(__Method_RemovePermissionNode, serviceImpl.RemovePermissionNode)
          .AddMethod(__Method_RemovePermissionNodeFromGroup, serviceImpl.RemovePermissionNodeFromGroup).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DyPermissionServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_HasPermission, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyHasPermissionRequest, global::DysonNetwork.Shared.Proto.DyHasPermissionResponse>(serviceImpl.HasPermission));
      serviceBinder.AddMethod(__Method_GetPermission, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyGetPermissionRequest, global::DysonNetwork.Shared.Proto.DyGetPermissionResponse>(serviceImpl.GetPermission));
      serviceBinder.AddMethod(__Method_AddPermissionNode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeRequest, global::DysonNetwork.Shared.Proto.DyAddPermissionNodeResponse>(serviceImpl.AddPermissionNode));
      serviceBinder.AddMethod(__Method_AddPermissionNodeToGroup, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupRequest, global::DysonNetwork.Shared.Proto.DyAddPermissionNodeToGroupResponse>(serviceImpl.AddPermissionNodeToGroup));
      serviceBinder.AddMethod(__Method_RemovePermissionNode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeRequest, global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeResponse>(serviceImpl.RemovePermissionNode));
      serviceBinder.AddMethod(__Method_RemovePermissionNodeFromGroup, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupRequest, global::DysonNetwork.Shared.Proto.DyRemovePermissionNodeFromGroupResponse>(serviceImpl.RemovePermissionNodeFromGroup));
    }

  }
}
#endregion
