// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: post.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace DysonNetwork.Shared.Proto {
  public static partial class DyPostService
  {
    static readonly string __ServiceName = "proto.DyPostService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyGetPostRequest> __Marshaller_proto_DyGetPostRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyGetPostRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyPost> __Marshaller_proto_DyPost = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyPost.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyGetPostBatchRequest> __Marshaller_proto_DyGetPostBatchRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyGetPostBatchRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyGetPostBatchResponse> __Marshaller_proto_DyGetPostBatchResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyGetPostBatchResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DySearchPostsRequest> __Marshaller_proto_DySearchPostsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DySearchPostsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DySearchPostsResponse> __Marshaller_proto_DySearchPostsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DySearchPostsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyListPostsRequest> __Marshaller_proto_DyListPostsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyListPostsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyListPostsResponse> __Marshaller_proto_DyListPostsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyListPostsResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyGetPostRequest, global::DysonNetwork.Shared.Proto.DyPost> __Method_GetPost = new grpc::Method<global::DysonNetwork.Shared.Proto.DyGetPostRequest, global::DysonNetwork.Shared.Proto.DyPost>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPost",
        __Marshaller_proto_DyGetPostRequest,
        __Marshaller_proto_DyPost);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyGetPostBatchRequest, global::DysonNetwork.Shared.Proto.DyGetPostBatchResponse> __Method_GetPostBatch = new grpc::Method<global::DysonNetwork.Shared.Proto.DyGetPostBatchRequest, global::DysonNetwork.Shared.Proto.DyGetPostBatchResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPostBatch",
        __Marshaller_proto_DyGetPostBatchRequest,
        __Marshaller_proto_DyGetPostBatchResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DySearchPostsRequest, global::DysonNetwork.Shared.Proto.DySearchPostsResponse> __Method_SearchPosts = new grpc::Method<global::DysonNetwork.Shared.Proto.DySearchPostsRequest, global::DysonNetwork.Shared.Proto.DySearchPostsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SearchPosts",
        __Marshaller_proto_DySearchPostsRequest,
        __Marshaller_proto_DySearchPostsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyListPostsRequest, global::DysonNetwork.Shared.Proto.DyListPostsResponse> __Method_ListPosts = new grpc::Method<global::DysonNetwork.Shared.Proto.DyListPostsRequest, global::DysonNetwork.Shared.Proto.DyListPostsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListPosts",
        __Marshaller_proto_DyListPostsRequest,
        __Marshaller_proto_DyListPostsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DysonNetwork.Shared.Proto.PostReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DyPostService</summary>
    [grpc::BindServiceMethod(typeof(DyPostService), "BindService")]
    public abstract partial class DyPostServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyPost> GetPost(global::DysonNetwork.Shared.Proto.DyGetPostRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyGetPostBatchResponse> GetPostBatch(global::DysonNetwork.Shared.Proto.DyGetPostBatchRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DySearchPostsResponse> SearchPosts(global::DysonNetwork.Shared.Proto.DySearchPostsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyListPostsResponse> ListPosts(global::DysonNetwork.Shared.Proto.DyListPostsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DyPostService</summary>
    public partial class DyPostServiceClient : grpc::ClientBase<DyPostServiceClient>
    {
      /// <summary>Creates a new client for DyPostService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DyPostServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DyPostService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DyPostServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DyPostServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DyPostServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyPost GetPost(global::DysonNetwork.Shared.Proto.DyGetPostRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPost(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyPost GetPost(global::DysonNetwork.Shared.Proto.DyGetPostRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPost, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyPost> GetPostAsync(global::DysonNetwork.Shared.Proto.DyGetPostRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPostAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyPost> GetPostAsync(global::DysonNetwork.Shared.Proto.DyGetPostRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPost, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyGetPostBatchResponse GetPostBatch(global::DysonNetwork.Shared.Proto.DyGetPostBatchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPostBatch(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyGetPostBatchResponse GetPostBatch(global::DysonNetwork.Shared.Proto.DyGetPostBatchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPostBatch, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyGetPostBatchResponse> GetPostBatchAsync(global::DysonNetwork.Shared.Proto.DyGetPostBatchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPostBatchAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyGetPostBatchResponse> GetPostBatchAsync(global::DysonNetwork.Shared.Proto.DyGetPostBatchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPostBatch, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DySearchPostsResponse SearchPosts(global::DysonNetwork.Shared.Proto.DySearchPostsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchPosts(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DySearchPostsResponse SearchPosts(global::DysonNetwork.Shared.Proto.DySearchPostsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SearchPosts, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DySearchPostsResponse> SearchPostsAsync(global::DysonNetwork.Shared.Proto.DySearchPostsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchPostsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DySearchPostsResponse> SearchPostsAsync(global::DysonNetwork.Shared.Proto.DySearchPostsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SearchPosts, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyListPostsResponse ListPosts(global::DysonNetwork.Shared.Proto.DyListPostsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListPosts(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyListPostsResponse ListPosts(global::DysonNetwork.Shared.Proto.DyListPostsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListPosts, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyListPostsResponse> ListPostsAsync(global::DysonNetwork.Shared.Proto.DyListPostsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListPostsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyListPostsResponse> ListPostsAsync(global::DysonNetwork.Shared.Proto.DyListPostsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListPosts, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DyPostServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DyPostServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DyPostServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetPost, serviceImpl.GetPost)
          .AddMethod(__Method_GetPostBatch, serviceImpl.GetPostBatch)
          .AddMethod(__Method_SearchPosts, serviceImpl.SearchPosts)
          .AddMethod(__Method_ListPosts, serviceImpl.ListPosts).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DyPostServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetPost, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyGetPostRequest, global::DysonNetwork.Shared.Proto.DyPost>(serviceImpl.GetPost));
      serviceBinder.AddMethod(__Method_GetPostBatch, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyGetPostBatchRequest, global::DysonNetwork.Shared.Proto.DyGetPostBatchResponse>(serviceImpl.GetPostBatch));
      serviceBinder.AddMethod(__Method_SearchPosts, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DySearchPostsRequest, global::DysonNetwork.Shared.Proto.DySearchPostsResponse>(serviceImpl.SearchPosts));
      serviceBinder.AddMethod(__Method_ListPosts, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyListPostsRequest, global::DysonNetwork.Shared.Proto.DyListPostsResponse>(serviceImpl.ListPosts));
    }

  }
}
#endregion
