// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: wallet.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace DysonNetwork.Shared.Proto {
  public static partial class DyWalletService
  {
    static readonly string __ServiceName = "proto.DyWalletService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyGetWalletRequest> __Marshaller_proto_DyGetWalletRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyGetWalletRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyWallet> __Marshaller_proto_DyWallet = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyWallet.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyCreateWalletRequest> __Marshaller_proto_DyCreateWalletRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyCreateWalletRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyGetOrCreateWalletPocketRequest> __Marshaller_proto_DyGetOrCreateWalletPocketRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyGetOrCreateWalletPocketRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyWalletPocket> __Marshaller_proto_DyWalletPocket = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyWalletPocket.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyGetWalletRequest, global::DysonNetwork.Shared.Proto.DyWallet> __Method_GetWallet = new grpc::Method<global::DysonNetwork.Shared.Proto.DyGetWalletRequest, global::DysonNetwork.Shared.Proto.DyWallet>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetWallet",
        __Marshaller_proto_DyGetWalletRequest,
        __Marshaller_proto_DyWallet);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyCreateWalletRequest, global::DysonNetwork.Shared.Proto.DyWallet> __Method_CreateWallet = new grpc::Method<global::DysonNetwork.Shared.Proto.DyCreateWalletRequest, global::DysonNetwork.Shared.Proto.DyWallet>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateWallet",
        __Marshaller_proto_DyCreateWalletRequest,
        __Marshaller_proto_DyWallet);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyGetOrCreateWalletPocketRequest, global::DysonNetwork.Shared.Proto.DyWalletPocket> __Method_GetOrCreateWalletPocket = new grpc::Method<global::DysonNetwork.Shared.Proto.DyGetOrCreateWalletPocketRequest, global::DysonNetwork.Shared.Proto.DyWalletPocket>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOrCreateWalletPocket",
        __Marshaller_proto_DyGetOrCreateWalletPocketRequest,
        __Marshaller_proto_DyWalletPocket);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DysonNetwork.Shared.Proto.WalletReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DyWalletService</summary>
    [grpc::BindServiceMethod(typeof(DyWalletService), "BindService")]
    public abstract partial class DyWalletServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyWallet> GetWallet(global::DysonNetwork.Shared.Proto.DyGetWalletRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyWallet> CreateWallet(global::DysonNetwork.Shared.Proto.DyCreateWalletRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyWalletPocket> GetOrCreateWalletPocket(global::DysonNetwork.Shared.Proto.DyGetOrCreateWalletPocketRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DyWalletService</summary>
    public partial class DyWalletServiceClient : grpc::ClientBase<DyWalletServiceClient>
    {
      /// <summary>Creates a new client for DyWalletService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DyWalletServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DyWalletService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DyWalletServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DyWalletServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DyWalletServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyWallet GetWallet(global::DysonNetwork.Shared.Proto.DyGetWalletRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWallet(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyWallet GetWallet(global::DysonNetwork.Shared.Proto.DyGetWalletRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetWallet, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyWallet> GetWalletAsync(global::DysonNetwork.Shared.Proto.DyGetWalletRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWalletAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyWallet> GetWalletAsync(global::DysonNetwork.Shared.Proto.DyGetWalletRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetWallet, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyWallet CreateWallet(global::DysonNetwork.Shared.Proto.DyCreateWalletRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateWallet(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyWallet CreateWallet(global::DysonNetwork.Shared.Proto.DyCreateWalletRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateWallet, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyWallet> CreateWalletAsync(global::DysonNetwork.Shared.Proto.DyCreateWalletRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateWalletAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyWallet> CreateWalletAsync(global::DysonNetwork.Shared.Proto.DyCreateWalletRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateWallet, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyWalletPocket GetOrCreateWalletPocket(global::DysonNetwork.Shared.Proto.DyGetOrCreateWalletPocketRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOrCreateWalletPocket(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyWalletPocket GetOrCreateWalletPocket(global::DysonNetwork.Shared.Proto.DyGetOrCreateWalletPocketRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOrCreateWalletPocket, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyWalletPocket> GetOrCreateWalletPocketAsync(global::DysonNetwork.Shared.Proto.DyGetOrCreateWalletPocketRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOrCreateWalletPocketAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyWalletPocket> GetOrCreateWalletPocketAsync(global::DysonNetwork.Shared.Proto.DyGetOrCreateWalletPocketRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOrCreateWalletPocket, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DyWalletServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DyWalletServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DyWalletServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetWallet, serviceImpl.GetWallet)
          .AddMethod(__Method_CreateWallet, serviceImpl.CreateWallet)
          .AddMethod(__Method_GetOrCreateWalletPocket, serviceImpl.GetOrCreateWalletPocket).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DyWalletServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetWallet, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyGetWalletRequest, global::DysonNetwork.Shared.Proto.DyWallet>(serviceImpl.GetWallet));
      serviceBinder.AddMethod(__Method_CreateWallet, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyCreateWalletRequest, global::DysonNetwork.Shared.Proto.DyWallet>(serviceImpl.CreateWallet));
      serviceBinder.AddMethod(__Method_GetOrCreateWalletPocket, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyGetOrCreateWalletPocketRequest, global::DysonNetwork.Shared.Proto.DyWalletPocket>(serviceImpl.GetOrCreateWalletPocket));
    }

  }
  public static partial class DyPaymentService
  {
    static readonly string __ServiceName = "proto.DyPaymentService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyCreateOrderRequest> __Marshaller_proto_DyCreateOrderRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyCreateOrderRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyOrder> __Marshaller_proto_DyOrder = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyOrder.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyCreateTransactionWithAccountRequest> __Marshaller_proto_DyCreateTransactionWithAccountRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyCreateTransactionWithAccountRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyTransaction> __Marshaller_proto_DyTransaction = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyTransaction.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyCreateTransactionRequest> __Marshaller_proto_DyCreateTransactionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyCreateTransactionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyCancelOrderRequest> __Marshaller_proto_DyCancelOrderRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyCancelOrderRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyRefundOrderRequest> __Marshaller_proto_DyRefundOrderRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyRefundOrderRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyRefundOrderResponse> __Marshaller_proto_DyRefundOrderResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyRefundOrderResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyTransferRequest> __Marshaller_proto_DyTransferRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyTransferRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyGetWalletFundRequest> __Marshaller_proto_DyGetWalletFundRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyGetWalletFundRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyWalletFund> __Marshaller_proto_DyWalletFund = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyWalletFund.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyCreateOrderRequest, global::DysonNetwork.Shared.Proto.DyOrder> __Method_CreateOrder = new grpc::Method<global::DysonNetwork.Shared.Proto.DyCreateOrderRequest, global::DysonNetwork.Shared.Proto.DyOrder>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateOrder",
        __Marshaller_proto_DyCreateOrderRequest,
        __Marshaller_proto_DyOrder);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyCreateTransactionWithAccountRequest, global::DysonNetwork.Shared.Proto.DyTransaction> __Method_CreateTransactionWithAccount = new grpc::Method<global::DysonNetwork.Shared.Proto.DyCreateTransactionWithAccountRequest, global::DysonNetwork.Shared.Proto.DyTransaction>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateTransactionWithAccount",
        __Marshaller_proto_DyCreateTransactionWithAccountRequest,
        __Marshaller_proto_DyTransaction);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyCreateTransactionRequest, global::DysonNetwork.Shared.Proto.DyTransaction> __Method_CreateTransaction = new grpc::Method<global::DysonNetwork.Shared.Proto.DyCreateTransactionRequest, global::DysonNetwork.Shared.Proto.DyTransaction>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateTransaction",
        __Marshaller_proto_DyCreateTransactionRequest,
        __Marshaller_proto_DyTransaction);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyCancelOrderRequest, global::DysonNetwork.Shared.Proto.DyOrder> __Method_CancelOrder = new grpc::Method<global::DysonNetwork.Shared.Proto.DyCancelOrderRequest, global::DysonNetwork.Shared.Proto.DyOrder>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CancelOrder",
        __Marshaller_proto_DyCancelOrderRequest,
        __Marshaller_proto_DyOrder);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyRefundOrderRequest, global::DysonNetwork.Shared.Proto.DyRefundOrderResponse> __Method_RefundOrder = new grpc::Method<global::DysonNetwork.Shared.Proto.DyRefundOrderRequest, global::DysonNetwork.Shared.Proto.DyRefundOrderResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RefundOrder",
        __Marshaller_proto_DyRefundOrderRequest,
        __Marshaller_proto_DyRefundOrderResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyTransferRequest, global::DysonNetwork.Shared.Proto.DyTransaction> __Method_Transfer = new grpc::Method<global::DysonNetwork.Shared.Proto.DyTransferRequest, global::DysonNetwork.Shared.Proto.DyTransaction>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Transfer",
        __Marshaller_proto_DyTransferRequest,
        __Marshaller_proto_DyTransaction);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyGetWalletFundRequest, global::DysonNetwork.Shared.Proto.DyWalletFund> __Method_GetWalletFund = new grpc::Method<global::DysonNetwork.Shared.Proto.DyGetWalletFundRequest, global::DysonNetwork.Shared.Proto.DyWalletFund>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetWalletFund",
        __Marshaller_proto_DyGetWalletFundRequest,
        __Marshaller_proto_DyWalletFund);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DysonNetwork.Shared.Proto.WalletReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of DyPaymentService</summary>
    [grpc::BindServiceMethod(typeof(DyPaymentService), "BindService")]
    public abstract partial class DyPaymentServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyOrder> CreateOrder(global::DysonNetwork.Shared.Proto.DyCreateOrderRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyTransaction> CreateTransactionWithAccount(global::DysonNetwork.Shared.Proto.DyCreateTransactionWithAccountRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyTransaction> CreateTransaction(global::DysonNetwork.Shared.Proto.DyCreateTransactionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyOrder> CancelOrder(global::DysonNetwork.Shared.Proto.DyCancelOrderRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyRefundOrderResponse> RefundOrder(global::DysonNetwork.Shared.Proto.DyRefundOrderRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyTransaction> Transfer(global::DysonNetwork.Shared.Proto.DyTransferRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyWalletFund> GetWalletFund(global::DysonNetwork.Shared.Proto.DyGetWalletFundRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DyPaymentService</summary>
    public partial class DyPaymentServiceClient : grpc::ClientBase<DyPaymentServiceClient>
    {
      /// <summary>Creates a new client for DyPaymentService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DyPaymentServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DyPaymentService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DyPaymentServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DyPaymentServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DyPaymentServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyOrder CreateOrder(global::DysonNetwork.Shared.Proto.DyCreateOrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateOrder(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyOrder CreateOrder(global::DysonNetwork.Shared.Proto.DyCreateOrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateOrder, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyOrder> CreateOrderAsync(global::DysonNetwork.Shared.Proto.DyCreateOrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateOrderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyOrder> CreateOrderAsync(global::DysonNetwork.Shared.Proto.DyCreateOrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateOrder, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyTransaction CreateTransactionWithAccount(global::DysonNetwork.Shared.Proto.DyCreateTransactionWithAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateTransactionWithAccount(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyTransaction CreateTransactionWithAccount(global::DysonNetwork.Shared.Proto.DyCreateTransactionWithAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateTransactionWithAccount, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyTransaction> CreateTransactionWithAccountAsync(global::DysonNetwork.Shared.Proto.DyCreateTransactionWithAccountRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateTransactionWithAccountAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyTransaction> CreateTransactionWithAccountAsync(global::DysonNetwork.Shared.Proto.DyCreateTransactionWithAccountRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateTransactionWithAccount, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyTransaction CreateTransaction(global::DysonNetwork.Shared.Proto.DyCreateTransactionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateTransaction(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyTransaction CreateTransaction(global::DysonNetwork.Shared.Proto.DyCreateTransactionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateTransaction, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyTransaction> CreateTransactionAsync(global::DysonNetwork.Shared.Proto.DyCreateTransactionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateTransactionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyTransaction> CreateTransactionAsync(global::DysonNetwork.Shared.Proto.DyCreateTransactionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateTransaction, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyOrder CancelOrder(global::DysonNetwork.Shared.Proto.DyCancelOrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CancelOrder(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyOrder CancelOrder(global::DysonNetwork.Shared.Proto.DyCancelOrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CancelOrder, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyOrder> CancelOrderAsync(global::DysonNetwork.Shared.Proto.DyCancelOrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CancelOrderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyOrder> CancelOrderAsync(global::DysonNetwork.Shared.Proto.DyCancelOrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CancelOrder, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyRefundOrderResponse RefundOrder(global::DysonNetwork.Shared.Proto.DyRefundOrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RefundOrder(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyRefundOrderResponse RefundOrder(global::DysonNetwork.Shared.Proto.DyRefundOrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RefundOrder, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyRefundOrderResponse> RefundOrderAsync(global::DysonNetwork.Shared.Proto.DyRefundOrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RefundOrderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyRefundOrderResponse> RefundOrderAsync(global::DysonNetwork.Shared.Proto.DyRefundOrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RefundOrder, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyTransaction Transfer(global::DysonNetwork.Shared.Proto.DyTransferRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Transfer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyTransaction Transfer(global::DysonNetwork.Shared.Proto.DyTransferRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Transfer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyTransaction> TransferAsync(global::DysonNetwork.Shared.Proto.DyTransferRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyTransaction> TransferAsync(global::DysonNetwork.Shared.Proto.DyTransferRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Transfer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyWalletFund GetWalletFund(global::DysonNetwork.Shared.Proto.DyGetWalletFundRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWalletFund(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyWalletFund GetWalletFund(global::DysonNetwork.Shared.Proto.DyGetWalletFundRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetWalletFund, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyWalletFund> GetWalletFundAsync(global::DysonNetwork.Shared.Proto.DyGetWalletFundRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWalletFundAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyWalletFund> GetWalletFundAsync(global::DysonNetwork.Shared.Proto.DyGetWalletFundRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetWalletFund, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DyPaymentServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DyPaymentServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DyPaymentServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateOrder, serviceImpl.CreateOrder)
          .AddMethod(__Method_CreateTransactionWithAccount, serviceImpl.CreateTransactionWithAccount)
          .AddMethod(__Method_CreateTransaction, serviceImpl.CreateTransaction)
          .AddMethod(__Method_CancelOrder, serviceImpl.CancelOrder)
          .AddMethod(__Method_RefundOrder, serviceImpl.RefundOrder)
          .AddMethod(__Method_Transfer, serviceImpl.Transfer)
          .AddMethod(__Method_GetWalletFund, serviceImpl.GetWalletFund).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DyPaymentServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateOrder, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyCreateOrderRequest, global::DysonNetwork.Shared.Proto.DyOrder>(serviceImpl.CreateOrder));
      serviceBinder.AddMethod(__Method_CreateTransactionWithAccount, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyCreateTransactionWithAccountRequest, global::DysonNetwork.Shared.Proto.DyTransaction>(serviceImpl.CreateTransactionWithAccount));
      serviceBinder.AddMethod(__Method_CreateTransaction, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyCreateTransactionRequest, global::DysonNetwork.Shared.Proto.DyTransaction>(serviceImpl.CreateTransaction));
      serviceBinder.AddMethod(__Method_CancelOrder, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyCancelOrderRequest, global::DysonNetwork.Shared.Proto.DyOrder>(serviceImpl.CancelOrder));
      serviceBinder.AddMethod(__Method_RefundOrder, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyRefundOrderRequest, global::DysonNetwork.Shared.Proto.DyRefundOrderResponse>(serviceImpl.RefundOrder));
      serviceBinder.AddMethod(__Method_Transfer, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyTransferRequest, global::DysonNetwork.Shared.Proto.DyTransaction>(serviceImpl.Transfer));
      serviceBinder.AddMethod(__Method_GetWalletFund, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyGetWalletFundRequest, global::DysonNetwork.Shared.Proto.DyWalletFund>(serviceImpl.GetWalletFund));
    }

  }
  public static partial class DySubscriptionService
  {
    static readonly string __ServiceName = "proto.DySubscriptionService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyGetSubscriptionRequest> __Marshaller_proto_DyGetSubscriptionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyGetSubscriptionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DySubscription> __Marshaller_proto_DySubscription = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DySubscription.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionRequest> __Marshaller_proto_DyGetPerkSubscriptionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsRequest> __Marshaller_proto_DyGetPerkSubscriptionsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsResponse> __Marshaller_proto_DyGetPerkSubscriptionsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyCreateSubscriptionRequest> __Marshaller_proto_DyCreateSubscriptionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyCreateSubscriptionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DysonNetwork.Shared.Proto.DyCancelSubscriptionRequest> __Marshaller_proto_DyCancelSubscriptionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DysonNetwork.Shared.Proto.DyCancelSubscriptionRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyGetSubscriptionRequest, global::DysonNetwork.Shared.Proto.DySubscription> __Method_GetSubscription = new grpc::Method<global::DysonNetwork.Shared.Proto.DyGetSubscriptionRequest, global::DysonNetwork.Shared.Proto.DySubscription>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSubscription",
        __Marshaller_proto_DyGetSubscriptionRequest,
        __Marshaller_proto_DySubscription);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionRequest, global::DysonNetwork.Shared.Proto.DySubscription> __Method_GetPerkSubscription = new grpc::Method<global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionRequest, global::DysonNetwork.Shared.Proto.DySubscription>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPerkSubscription",
        __Marshaller_proto_DyGetPerkSubscriptionRequest,
        __Marshaller_proto_DySubscription);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsRequest, global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsResponse> __Method_GetPerkSubscriptions = new grpc::Method<global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsRequest, global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPerkSubscriptions",
        __Marshaller_proto_DyGetPerkSubscriptionsRequest,
        __Marshaller_proto_DyGetPerkSubscriptionsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyCreateSubscriptionRequest, global::DysonNetwork.Shared.Proto.DySubscription> __Method_CreateSubscription = new grpc::Method<global::DysonNetwork.Shared.Proto.DyCreateSubscriptionRequest, global::DysonNetwork.Shared.Proto.DySubscription>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateSubscription",
        __Marshaller_proto_DyCreateSubscriptionRequest,
        __Marshaller_proto_DySubscription);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DysonNetwork.Shared.Proto.DyCancelSubscriptionRequest, global::DysonNetwork.Shared.Proto.DySubscription> __Method_CancelSubscription = new grpc::Method<global::DysonNetwork.Shared.Proto.DyCancelSubscriptionRequest, global::DysonNetwork.Shared.Proto.DySubscription>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CancelSubscription",
        __Marshaller_proto_DyCancelSubscriptionRequest,
        __Marshaller_proto_DySubscription);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DysonNetwork.Shared.Proto.WalletReflection.Descriptor.Services[2]; }
    }

    /// <summary>Base class for server-side implementations of DySubscriptionService</summary>
    [grpc::BindServiceMethod(typeof(DySubscriptionService), "BindService")]
    public abstract partial class DySubscriptionServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DySubscription> GetSubscription(global::DysonNetwork.Shared.Proto.DyGetSubscriptionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DySubscription> GetPerkSubscription(global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsResponse> GetPerkSubscriptions(global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DySubscription> CreateSubscription(global::DysonNetwork.Shared.Proto.DyCreateSubscriptionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DysonNetwork.Shared.Proto.DySubscription> CancelSubscription(global::DysonNetwork.Shared.Proto.DyCancelSubscriptionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DySubscriptionService</summary>
    public partial class DySubscriptionServiceClient : grpc::ClientBase<DySubscriptionServiceClient>
    {
      /// <summary>Creates a new client for DySubscriptionService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DySubscriptionServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DySubscriptionService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DySubscriptionServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DySubscriptionServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DySubscriptionServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DySubscription GetSubscription(global::DysonNetwork.Shared.Proto.DyGetSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSubscription(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DySubscription GetSubscription(global::DysonNetwork.Shared.Proto.DyGetSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSubscription, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DySubscription> GetSubscriptionAsync(global::DysonNetwork.Shared.Proto.DyGetSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSubscriptionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DySubscription> GetSubscriptionAsync(global::DysonNetwork.Shared.Proto.DyGetSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSubscription, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DySubscription GetPerkSubscription(global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPerkSubscription(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DySubscription GetPerkSubscription(global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPerkSubscription, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DySubscription> GetPerkSubscriptionAsync(global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPerkSubscriptionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DySubscription> GetPerkSubscriptionAsync(global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPerkSubscription, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsResponse GetPerkSubscriptions(global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPerkSubscriptions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsResponse GetPerkSubscriptions(global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPerkSubscriptions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsResponse> GetPerkSubscriptionsAsync(global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPerkSubscriptionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsResponse> GetPerkSubscriptionsAsync(global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPerkSubscriptions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DySubscription CreateSubscription(global::DysonNetwork.Shared.Proto.DyCreateSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateSubscription(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DySubscription CreateSubscription(global::DysonNetwork.Shared.Proto.DyCreateSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateSubscription, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DySubscription> CreateSubscriptionAsync(global::DysonNetwork.Shared.Proto.DyCreateSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateSubscriptionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DySubscription> CreateSubscriptionAsync(global::DysonNetwork.Shared.Proto.DyCreateSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateSubscription, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DySubscription CancelSubscription(global::DysonNetwork.Shared.Proto.DyCancelSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CancelSubscription(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DysonNetwork.Shared.Proto.DySubscription CancelSubscription(global::DysonNetwork.Shared.Proto.DyCancelSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CancelSubscription, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DySubscription> CancelSubscriptionAsync(global::DysonNetwork.Shared.Proto.DyCancelSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CancelSubscriptionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DysonNetwork.Shared.Proto.DySubscription> CancelSubscriptionAsync(global::DysonNetwork.Shared.Proto.DyCancelSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CancelSubscription, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DySubscriptionServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DySubscriptionServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DySubscriptionServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetSubscription, serviceImpl.GetSubscription)
          .AddMethod(__Method_GetPerkSubscription, serviceImpl.GetPerkSubscription)
          .AddMethod(__Method_GetPerkSubscriptions, serviceImpl.GetPerkSubscriptions)
          .AddMethod(__Method_CreateSubscription, serviceImpl.CreateSubscription)
          .AddMethod(__Method_CancelSubscription, serviceImpl.CancelSubscription).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DySubscriptionServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetSubscription, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyGetSubscriptionRequest, global::DysonNetwork.Shared.Proto.DySubscription>(serviceImpl.GetSubscription));
      serviceBinder.AddMethod(__Method_GetPerkSubscription, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionRequest, global::DysonNetwork.Shared.Proto.DySubscription>(serviceImpl.GetPerkSubscription));
      serviceBinder.AddMethod(__Method_GetPerkSubscriptions, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsRequest, global::DysonNetwork.Shared.Proto.DyGetPerkSubscriptionsResponse>(serviceImpl.GetPerkSubscriptions));
      serviceBinder.AddMethod(__Method_CreateSubscription, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyCreateSubscriptionRequest, global::DysonNetwork.Shared.Proto.DySubscription>(serviceImpl.CreateSubscription));
      serviceBinder.AddMethod(__Method_CancelSubscription, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DysonNetwork.Shared.Proto.DyCancelSubscriptionRequest, global::DysonNetwork.Shared.Proto.DySubscription>(serviceImpl.CancelSubscription));
    }

  }
}
#endregion
