//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DysonNetwork.Sphere.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountEventResource_zh_CN {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountEventResource_zh_CN() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DysonNetwork.Sphere.Resources.AccountEventResource_zh_CN", typeof(AccountEventResource_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FortuneTipPositiveTitle_1 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveTitle_1", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveContent_1 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveContent_1", resourceCulture);
            }
        }
        
        internal static string FortuneTipNegativeTitle_1_ {
            get {
                return ResourceManager.GetString("FortuneTipNegativeTitle_1 ", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveTitle_2 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveTitle_2", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveContent_2 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveContent_2", resourceCulture);
            }
        }
        
        internal static string FortuneTipNegativeTitle_2 {
            get {
                return ResourceManager.GetString("FortuneTipNegativeTitle_2", resourceCulture);
            }
        }
        
        internal static string FortuneTipNegativeContent_2 {
            get {
                return ResourceManager.GetString("FortuneTipNegativeContent_2", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveTitle_3 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveTitle_3", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveContent_3 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveContent_3", resourceCulture);
            }
        }
        
        internal static string FortuneTipNegativeTitle_3 {
            get {
                return ResourceManager.GetString("FortuneTipNegativeTitle_3", resourceCulture);
            }
        }
        
        internal static string FortuneTipNegativeContent_3 {
            get {
                return ResourceManager.GetString("FortuneTipNegativeContent_3", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveTitle_4 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveTitle_4", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveContent_4 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveContent_4", resourceCulture);
            }
        }
        
        internal static string FortuneTipNegativeTitle_4 {
            get {
                return ResourceManager.GetString("FortuneTipNegativeTitle_4", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveTitle_5 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveTitle_5", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveContent_5 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveContent_5", resourceCulture);
            }
        }
        
        internal static string FortuneTipNegativeTitle_5 {
            get {
                return ResourceManager.GetString("FortuneTipNegativeTitle_5", resourceCulture);
            }
        }
        
        internal static string FortuneTipNegativeContent_5 {
            get {
                return ResourceManager.GetString("FortuneTipNegativeContent_5", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveTitle_6 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveTitle_6", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveContent_6 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveContent_6", resourceCulture);
            }
        }
        
        internal static string FortuneTipNegativeTitle_6 {
            get {
                return ResourceManager.GetString("FortuneTipNegativeTitle_6", resourceCulture);
            }
        }
        
        internal static string FortuneTipNegativeContent_6 {
            get {
                return ResourceManager.GetString("FortuneTipNegativeContent_6", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveTitle_7 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveTitle_7", resourceCulture);
            }
        }
        
        internal static string FortuneTipPositiveContent_7 {
            get {
                return ResourceManager.GetString("FortuneTipPositiveContent_7", resourceCulture);
            }
        }
        
        internal static string FortuneTipNegativeTitle_7 {
            get {
                return ResourceManager.GetString("FortuneTipNegativeTitle_7", resourceCulture);
            }
        }
        
        internal static string FortuneTipNegativeContent_7 {
            get {
                return ResourceManager.GetString("FortuneTipNegativeContent_7", resourceCulture);
            }
        }
    }
}
